# Generated by Django 2.0.2 on 2018-02-20 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcustomer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appmerchant',
            name='cert_file',
            field=models.FileField(blank=True, null=True, upload_to='cert', verbose_name='证书文件'),
        ),
        migrations.AlterField(
            model_name='appmerchant',
            name='key_file',
            field=models.FileField(blank=True, null=True, upload_to='cert', verbose_name='密钥文件'),
        ),
        migrations.AlterField(
            model_name='appmerchant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
