# Generated by Django 2.0.2 on 2018-02-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('feature', models.CharField(blank=True, max_length=512, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=11, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('icon', models.ImageField(upload_to='shopinfo/icon')),
            ],
        ),
    ]
