# Generated by Django 2.0.2 on 2018-02-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0002_shopinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='shopinfo/icon'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
