# Generated by Django 2.0.2 on 2018-02-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0003_auto_20180221_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcustomer',
            name='user_info',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='用户信息'),
        ),
    ]
