# Generated by Django 2.0.2 on 2018-02-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0003_auto_20180206_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopinfo',
            options={'verbose_name': '店铺', 'verbose_name_plural': '店铺管理'},
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='店铺描述'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='feature',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='店铺特色'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='shopinfo/icon', verbose_name='店铺图标'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='name',
            field=models.CharField(max_length=32, verbose_name='店铺名称'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='phone_num',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='店铺类型'),
        ),
    ]
