# Generated by Django 2.0.2 on 2018-02-20 18:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_auto_20180221_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcustomer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appcustomer',
            name='openid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='微信OpenId'),
        ),
        migrations.AlterField(
            model_name='appcustomer',
            name='session_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='会话密钥'),
        ),
        migrations.AlterField(
            model_name='appcustomer',
            name='type',
            field=models.CharField(default='appcst', max_length=16, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='appcustomer',
            name='unionid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='统一Id'),
        ),
    ]
