# Generated by Django 2.0.2 on 2018-02-06 20:51

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_auto_20180206_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='description',
            field=models.TextField(blank=True, help_text='最多500个字符，250个汉字', max_length=512, null=True, verbose_name='店铺描述'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='feature',
            field=models.TextField(blank=True, help_text='最多500个字符，250个汉字', max_length=512, null=True, verbose_name='店铺特色'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='icon',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='shopinfo/icon', verbose_name='店铺图标'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='type',
            field=models.CharField(blank=True, help_text='自定义店铺类型，32个字符以内', max_length=32, null=True, verbose_name='店铺类型'),
        ),
    ]
