# Generated by Django 2.0.2 on 2018-02-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0005_auto_20180206_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='shopinfo/icon', verbose_name='店铺图标'),
        ),
    ]
