# Generated by Django 2.0.2 on 2018-02-06 21:27

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0006_auto_20180206_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('icon', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
