# Generated by Django 2.0.2 on 2018-02-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0006_remove_appcustomer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcustomer',
            name='user_info',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='用户信息'),
        ),
    ]
