# Generated by Django 2.0.2 on 2018-02-21 04:37

from django.db import migrations, models
import django.db.models.deletion
import estore.imagefieldex


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0007_auto_20180221_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='最多500个字符，250个汉字', max_length=512, verbose_name='内容')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
            },
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='banners',
            field=estore.imagefieldex.ManyToManyFieldEx(blank=True, related_name='banners', to='estore.Picture', verbose_name='广告图片'),
        ),
        migrations.AddField(
            model_name='notice',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.ShopInfo', verbose_name='所属店铺'),
        ),
    ]
