# Generated by Django 2.0.2 on 2018-02-06 21:36

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0007_shopinfo_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='icon',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='shopinfo/icon', verbose_name='店铺图标'),
        ),
    ]
