# Generated by Django 2.0.2 on 2018-02-21 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0008_auto_20180221_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='estore.ShopInfo', verbose_name='所属店铺'),
        ),
    ]
