# Generated by Django 2.0.2 on 2018-02-06 22:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0008_auto_20180206_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=11, null=True, verbose_name='联系电话'),
        ),
    ]
