# Generated by Django 2.0.2 on 2018-02-21 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0009_auto_20180221_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='belong',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='estore.ShopInfo'),
        ),
    ]
