# Generated by Django 2.0.2 on 2018-02-08 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import estore.imagefieldex


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estore', '0010_auto_20180207_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='icon',
            field=estore.imagefieldex.ImageFieldEx(blank=True, null=True, upload_to='shopinfo/icon', verbose_name='店铺图标'),
        ),
    ]
