# Generated by Django 2.0.2 on 2018-02-21 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0010_product_belong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='estore.ShopInfo', verbose_name='所属商铺'),
        ),
    ]
