# Generated by Django 2.0.2 on 2018-02-21 10:16

from django.db import migrations, models
import django.db.models.deletion
import estore.imagefieldex


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0011_auto_20180221_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off_price',
            field=models.FloatField(blank=True, null=True, verbose_name='折扣价格'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_pic',
            field=estore.imagefieldex.OneToOneFieldEx(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary', to='estore.Picture', verbose_name='首要图片'),
        ),
    ]
