# Generated by Django 2.0.2 on 2018-02-08 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0012_auto_20180208_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', related_query_name='parent', to='estore.GoodsCategory', verbose_name='上级分类'),
        ),
    ]
