# Generated by Django 2.0.2 on 2018-02-22 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0013_auto_20180222_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='estore.AppCustomer', verbose_name='客户'),
        ),
    ]
