# Generated by Django 2.0.2 on 2018-02-08 07:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estore', '0014_auto_20180208_0509'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goodscategory',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='goodscategory',
            order_with_respect_to='parent_category',
        ),
    ]
