# Generated by Django 2.0.2 on 2018-02-22 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0015_auto_20180222_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcustomer',
            name='basket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='estore.Basket', verbose_name='购物车'),
        ),
        migrations.AlterField(
            model_name='basketlineunit',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='estore.Basket', verbose_name='购物车'),
        ),
    ]
