# Generated by Django 2.0.2 on 2018-02-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0015_auto_20180208_0704'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='goodscategory',
            order_with_respect_to=None,
        ),
    ]
