# Generated by Django 2.0.2 on 2018-02-22 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0017_auto_20180222_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketlineunit',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='estore.Basket', verbose_name='购物车'),
        ),
        migrations.AlterField(
            model_name='basketlineunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_lines', to='estore.Product', verbose_name='商品'),
        ),
    ]
