# Generated by Django 2.0.2 on 2018-02-09 00:37

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0018_goodscategory2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscategory2',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='parent',
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='parent_category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='estore.GoodsCategory', verbose_name='上级分类'),
        ),
        migrations.DeleteModel(
            name='GoodsCategory2',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
