# Generated by Django 2.0.2 on 2018-02-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0018_auto_20180222_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcustomer',
            name='basket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='estore.Basket', verbose_name='购物车'),
        ),
    ]
