# Generated by Django 2.0.2 on 2018-02-09 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0019_auto_20180209_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscategory',
            name='parent_category',
        ),
    ]
