# Generated by Django 2.0.2 on 2018-02-09 00:45

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0020_remove_goodscategory_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategory',
            name='parent_category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='estore.GoodsCategory', verbose_name='上级分类'),
        ),
    ]
