# Generated by Django 2.0.2 on 2018-02-09 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0021_goodscategory_parent_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goodscategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='goodscategory',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='goodscategory',
            name='parent_category',
        ),
        migrations.DeleteModel(
            name='GoodsCategory',
        ),
    ]
