# Generated by Django 2.0.2 on 2018-02-09 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0023_auto_20180209_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodscategory',
            old_name='parent_category',
            new_name='parent',
        ),
    ]
