# Generated by Django 2.0.2 on 2018-02-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0024_auto_20180209_0054'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goodscategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='goodscategory',
            name='owner',
        ),
    ]
