# Generated by Django 2.0.2 on 2018-02-09 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0026_goodscategorywrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategorywrap',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estore.GoodsCategory'),
        ),
    ]
