# Generated by Django 2.0.2 on 2018-02-09 03:55

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0028_auto_20180209_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='estore.GoodsCategory', verbose_name='上级分类'),
        ),
    ]
