# Generated by Django 2.0.2 on 2018-02-11 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import estore.imagefieldex


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estore', '0031_auto_20180209_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('no', models.CharField(blank=True, max_length=32, null=True, verbose_name='编号')),
                ('bar_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='条码编号')),
                ('description', models.TextField(blank=True, help_text='最多500个字符，250个汉字', max_length=512, null=True, verbose_name='描述')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to=settings.AUTH_USER_MODEL, verbose_name='商户')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '3 商品管理',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', estore.imagefieldex.ImageFieldEx(blank=True, null=True, upload_to='estorepics', verbose_name='图片')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to=settings.AUTH_USER_MODEL, verbose_name='商户')),
            ],
        ),
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '商品分类', 'verbose_name_plural': '2 商品分类管理'},
        ),
        migrations.AlterModelOptions(
            name='shopinfo',
            options={'verbose_name': '店铺', 'verbose_name_plural': '1 店铺管理'},
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='商户'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='icon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estore.Picture', verbose_name='店铺图标'),
        ),
        migrations.AddField(
            model_name='goods',
            name='pics',
            field=models.ManyToManyField(blank=True, null=True, to='estore.Picture', verbose_name='图片'),
        ),
    ]
