# Generated by Django 2.0.2 on 2018-02-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0032_auto_20180211_0414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': '图片', 'verbose_name_plural': '4 图片管理'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='pics',
            field=models.ManyToManyField(blank=True, to='estore.Picture', verbose_name='图片'),
        ),
    ]
