# Generated by Django 2.0.2 on 2018-02-11 11:49

from django.db import migrations
import estore.imagefieldex


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0036_auto_20180211_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodspictures',
            name='picture',
            field=estore.imagefieldex.ImageFieldEx(blank=True, null=True, upload_to='estorepics/goods', verbose_name='图片'),
        ),
    ]
