# Generated by Django 2.0.2 on 2018-02-11 23:26

from django.db import migrations
import estore.imagefieldex


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0037_auto_20180211_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=estore.imagefieldex.ImageFieldEx(blank=True, null=True, upload_to='estorepics', verbose_name='图片'),
        ),
    ]
