# Generated by Django 2.0.2 on 2018-02-12 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0038_auto_20180211_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品管理'},
        ),
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '商品分类', 'verbose_name_plural': '商品分类管理'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': '图片', 'verbose_name_plural': '图片管理'},
        ),
        migrations.AlterModelOptions(
            name='shopinfo',
            options={'verbose_name': '店铺', 'verbose_name_plural': '店铺管理'},
        ),
    ]
