# Generated by Django 2.0.2 on 2018-02-12 01:24

from django.db import migrations, models
import estore.imagefieldex


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0039_auto_20180212_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='desc',
            field=models.CharField(default='desc', max_length=32, verbose_name='描述'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=estore.imagefieldex.ImageFieldEx(upload_to='estorepics', verbose_name='图片'),
        ),
    ]
