# Generated by Django 2.0.2 on 2018-02-12 04:00

from django.db import migrations
import django.db.models.deletion
import estore.imagefieldex


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0041_auto_20180212_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='icon',
            field=estore.imagefieldex.OneToOneFieldEx(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estore.Picture', verbose_name='店铺图标'),
        ),
    ]
