# Generated by Django 2.0.2 on 2018-02-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0043_auto_20180212_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pics',
            field=models.ManyToManyField(blank=True, to='estore.Picture', verbose_name='图片'),
        ),
    ]
