# Generated by Django 2.0.2 on 2018-02-12 13:56

from django.db import migrations
import estore.imagefieldex


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0044_auto_20180212_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pics',
            field=estore.imagefieldex.ManyToManyFieldEx(blank=True, to='estore.Picture', verbose_name='图片'),
        ),
    ]
